DCRProj/force-app/main/default/objects/DCR_Line__c/DCR_Line__c.object-meta.xml
<CustomObject>
    <label>DCR Line</label>
    <nameField>
        <displayFormat>DLI-{000000}</displayFormat>
        <label>DCR Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCR Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DCRProj/force-app/main/default/objects/DCR_Line__c/fields/DCRLineStatus__c.field-meta.xml
<CustomField>
    <fullName>DCRLineStatus__c</fullName>
    <label>DCRLineStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DCRProj/force-app/main/default/objects/DCR_Line__c/fields/Field_Source__c.field-meta.xml
<CustomField>
    <fullName>Field_Source__c</fullName>
    <label>Field Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DCRProj/force-app/main/default/classes/DCRDataTableApexClass.cls
public class DCRDataTableApexClass {
    @AuraEnabled
    public static List<DCR_Line__c> getAllDCRLineItems() {
        return [Select Id, Name, Field_Source__c, Field_Name__c, Old_Value__c, New_Value__c, DCRLineStatus__c from DCR_Line__c];
    }
    
    @AuraEnabled
    public static void updateDCR(List<DCR_Line__c> dcrLineItems) {
        for(DCR_Line__c dcrLineItem : dcrLineItems) {
            system.debug('dcrLineItem' + dcrLineItem);
            
            
            if (dcrLineItem.DCRLineStatus__c == 'Approved') {
             	
                // Update	 the Account or Address objects.
                if (dcrLineItem.Field_Source__c == 'Address') {
                    // Get address
                    // Update address
                    // address.put(dcrLineItem.Field_Name__c, dcrLineItem.New_Value__c);
                }
                else if (dcrLineItem.Field_Source__c == 'Account') {
                    
                }       
            }
        }
        
        update dcrLineItems;
    }
}